# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-28 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('old_quantity', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
                ('base_price', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('distributor_name', models.CharField(max_length=100)),
                ('distributor_no', models.IntegerField()),
                ('remark', models.CharField(max_length=1000)),
                ('expected_date_for_new_stock', models.DateField()),
                ('distributor_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pas', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=240)),
            ],
        ),
    ]
